spring.datasource.url=jdbc:postgresql://localhost:5432/market_db
spring.datasource.username=${MARKET_USER}
spring.datasource.password=${MARKET_PASS}

jwt.public-service-key-path=../certs/service-public.pem
jwt.public-key-path=../certs/public.pem