spring.datasource.url=jdbc:postgresql://postgres:5432/market_db
spring.datasource.username=postgres
spring.datasource.password=password

jwt.public-service-key-path=/app/certs/service-public.pem
jwt.public-key-path=/app/certs/public.pem

spring.kafka.bootstrap-servers=kafka:9092